name: Build .mpy files

on:
  push:
    tags:
      - '*'  # This will trigger the workflow for any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest version of Python

      - name: Install dependencies
        run: |
          pip install mpy-cross

      - name: Compile .mpy files
        run: |
          for file in *.py; do
            if [[ -f "$file" ]]; then
              mpy-cross "$file"
            fi
          done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the tag that triggered the workflow
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.OOCSI_CP_ACTIONS }}

      - name: Upload .mpy files to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: oocsi.mpy
          asset_name: oocsi.mpy
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.OOCSI_CP_ACTIONS }}
